#!/bin/sh
export ANDROID_SDK_PATH=/opt/android-sdk-update-manager
export ANDROID_NDK_PATH=/opt/android-ndk

pushd _andr
../../tools/configure --target=201 --type=n --lcdwidth=480 --lcdheight=800

make veryclean

make -j4

make zip apk

popd
